-- MySQL Script generated by MySQL Workbench
-- Sun Nov  5 11:49:48 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema productomicro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema productomicro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `productomicro` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `productomicro` ;

-- -----------------------------------------------------
-- Table `productomicro`.`almacen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `productomicro`.`almacen` (
  `id_almacen` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre_almacen` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_almacen`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `productomicro`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `productomicro`.`categoria` (
  `id_categoria` BIGINT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `productomicro`.`inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `productomicro`.`inventario` (
  `id_inventario` BIGINT NOT NULL AUTO_INCREMENT,
  `stock` DOUBLE NOT NULL,
  `stock_minimo` DOUBLE NOT NULL,
  `id_almacen` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id_inventario`),
  INDEX `FK5kmq4yv4bbrmxb8og7eojxyq1` (`id_almacen` ASC) VISIBLE,
  CONSTRAINT `FK5kmq4yv4bbrmxb8og7eojxyq1`
    FOREIGN KEY (`id_almacen`)
    REFERENCES `productomicro`.`almacen` (`id_almacen`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `productomicro`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `productomicro`.`marca` (
  `id_marca` BIGINT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_marca`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `productomicro`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `productomicro`.`producto` (
  `id_producto` BIGINT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(255) NULL DEFAULT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `fecha_caducidad` DATETIME(6) NULL DEFAULT NULL,
  `fecha_crea` DATETIME(6) NULL DEFAULT NULL,
  `fecha_mod` DATETIME(6) NULL DEFAULT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `precio` DOUBLE NULL DEFAULT NULL,
  `id_categoria` BIGINT NULL DEFAULT NULL,
  `id_inventario` BIGINT NULL DEFAULT NULL,
  `id_marca` BIGINT NULL DEFAULT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `FK9nyueixdsgbycfhf7allg8su` (`id_categoria` ASC) VISIBLE,
  INDEX `FKbiphtvkj4dh3gph3uvududcik` (`id_inventario` ASC) VISIBLE,
  INDEX `FKpmfw7ds3rfuwge05ehb216r82` (`id_marca` ASC) VISIBLE,
  CONSTRAINT `FK9nyueixdsgbycfhf7allg8su`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `productomicro`.`categoria` (`id_categoria`),
  CONSTRAINT `FKbiphtvkj4dh3gph3uvududcik`
    FOREIGN KEY (`id_inventario`)
    REFERENCES `productomicro`.`inventario` (`id_inventario`),
  CONSTRAINT `FKpmfw7ds3rfuwge05ehb216r82`
    FOREIGN KEY (`id_marca`)
    REFERENCES `productomicro`.`marca` (`id_marca`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
