-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.persona
(
    id_persona bigint NOT NULL DEFAULT nextval('persona_id_persona_seq'::regclass),
    apellidos character varying(255) COLLATE pg_catalog."default",
    celular character varying(255) COLLATE pg_catalog."default",
    direccion character varying(255) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default",
    estado integer NOT NULL,
    fecha_crea timestamp without time zone,
    fecha_mod timestamp without time zone,
    nombres character varying(255) COLLATE pg_catalog."default",
    sexo character varying(255) COLLATE pg_catalog."default",
    id_tipo_persona bigint,
    CONSTRAINT persona_pkey PRIMARY KEY (id_persona)
);

CREATE TABLE IF NOT EXISTS public.tipo_persona
(
    id_tipo_persona bigint NOT NULL DEFAULT nextval('tipo_persona_id_tipo_persona_seq'::regclass),
    denominacion character varying(255) COLLATE pg_catalog."default",
    descripcion character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT tipo_persona_pkey PRIMARY KEY (id_tipo_persona)
);

CREATE TABLE IF NOT EXISTS public.usuario
(
    id_usuario bigint NOT NULL DEFAULT nextval('usuario_id_usuario_seq'::regclass),
    estado integer NOT NULL,
    fecha_crea timestamp without time zone,
    fecha_mod timestamp without time zone,
    password character varying(255) COLLATE pg_catalog."default",
    rol character varying(255) COLLATE pg_catalog."default",
    usuario character varying(255) COLLATE pg_catalog."default",
    id_persona bigint,
    CONSTRAINT usuario_pkey PRIMARY KEY (id_usuario)
);

ALTER TABLE IF EXISTS public.persona
    ADD CONSTRAINT fk_persona_tipopersona FOREIGN KEY (id_tipo_persona)
    REFERENCES public.tipo_persona (id_tipo_persona) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.usuario
    ADD CONSTRAINT fkagix3q8yqktlyj3yp1sn0mcd9 FOREIGN KEY (id_persona)
    REFERENCES public.persona (id_persona) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;